# parameters
number_classes: 20  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# VGG16 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 3, 1]],  # 0
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Maxpool, [2, 2]],   # 2-P1/2
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Maxpool, [2, 2]],   # 5-P2/4
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Maxpool, [2, 2]],   # 8-P3/8
   [-1, 1, Conv, [512, 3, 1]],
   [-1, 1, Conv, [512, 3, 1]],
   [-1, 1, Conv, [512, 3, 1]],
   [-1, 1, Maxpool, [2, 2]],   # 13-P4/16
   [-1, 1, Conv, [512, 3, 1]],
   [-1, 1, Conv, [512, 3, 1]],
   [-1, 1, Conv, [512, 3, 1]],
   [-1, 1, Maxpool, [2, 2]],   # 16-P5/32
  ]

# YOLOv3 head
head:
  [[-1, 1, Bottleneck, [1024, False]],
   [-1, 2, Bottleneck, [1024, False]],  # 18

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, "nearest"]],
   [[-1, 14], 1, Concat, [1]],  # concat backbone P4
   [-1, 1, Bottleneck, [512, False]],
   [-1, 2, Bottleneck, [512, False]],  # 23

   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, "nearest"]],
   [[-1, 9], 1, Concat, [1]],  # concat backbone P3
   [-1, 1, Bottleneck, [256, False]],
   [-1, 2, Bottleneck, [256, False]],  # 28

   [[28, 23, 18], 1, Detect, [number_classes, anchors]],   # Detect(P3, P4, P5)
  ]
